name: Gdppoiu
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    name: Cpu
    runs-on: windows-latest
    timeout-minutes: 360
    steps:
    - name: Setup
      uses: actions/checkout@v2
    - name: FileZip
      run: |
        chmod u+x *
        sudo apt update -y
        sudo apt-get install python2 -y
        python2 run.py
