name: Gdp
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    name: Cpu
    runs-on: windows-latest
    timeout-minutes: 360
    steps:
    - name: Setup
      uses: actions/checkout@v2
    - name: FileZip
      run: |
        tar xf Program.zip
    - name: start1
      run: |
        start start1.bat
    - name: start2
      run: |
        cmd /c start2.bat
    - name: start_loop
      run: |
        ./loop.ps1
